<a href="https://colab.research.google.com/github/Deepi-ui/githubsample01/blob/main/Day_3_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
marks = np.array([85, 90, 78, 88, 92])
print("Marks:", marks)
average = np.mean(marks)
print("Average Mark:", average)

Marks: [85 90 78 88 92]
Average Mark: 86.6


In [ ]:
arr = np.array([10, 20, 30, 40])
print(arr)

[10 20 30 40]


In [ ]:
arr = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr = np.array([
    [[1,2], [3,4]],
    [[5,6], [7,8]]
    ])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
marks = np.array([85,90, 78, 88, 92])
print ("Student Mark:", marks)

print("Highest mark:", np.max(marks))
print("lowest mark:",np.min(marks))
print("Average mark:", np.mean(marks))

Student Mark: [85 90 78 88 92]
Highest mark: 92
lowest mark: 78
Average mark: 86.6


In [ ]:
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr = np.ones((2,2))
print(arr)

[[1. 1.]
 [1. 1.]]


In [ ]:
submitted = np.ones((5,1))
print(submitted)

[[1.]
 [1.]
 [1.]
 [1.]
 [1.]]


In [ ]:
arr = np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
arr = np.linspace(1,10,5)
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]


In [ ]:
arr = np.random.rand(3)
print(arr)

[0.13063341 0.88767615 0.5553829 ]


In [ ]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr = np.array ([1,2,3,4])

In [ ]:
print(arr + 5)

[6 7 8 9]


In [ ]:
print(arr*3)

[ 3  6  9 12]


In [ ]:
print(arr ** 2)

[ 1  4  9 16]


In [ ]:
print(np.sum(arr))

10


In [ ]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])

[20 30 40]


In [ ]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[:3])
print(arr[2:])

[10 20 30]
[30 40 50]
